version: '3.8'

services:
  mongodb:
    image: mongo:latest
    networks:
      - mongodb
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./docker/mongo
        target: /data/db

  mongo-express:
    image: mongo-express
    networks:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - qdrantdb

  watcher:
    networks:
      - mongodb
    ports:
      - 6301:6301
    build:
      context: .
      dockerfile: ./watcher/Dockerfile
    env_file:
      - .env

  summaryer:
    networks:
      - mongodb
      - qdrantdb
    build:
      context: .
      dockerfile: ./summaryer/Dockerfile
    env_file:
      - .env

networks:
  mongodb:
  qdrantdb:


